# Generated by Django 4.0 on 2022-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('your_mail', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
