# Generated by Django 4.0 on 2022-07-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='your_name',
            new_name='name',
        ),
    ]
